spring.application.name=DigiBankJWT

spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=eoZ2FMAgeDUJT3DS8FQ3jTg3iFKlEMaSVWczHcWIJaE
# Access token expiration (15 minutes)
jwt.expiration=900000
# Refresh token expiration (24 hours)
jwt.refreshExpiration=86400000
