spring.application.name=DigiBankJWT

spring.datasource.url=jdbc:postgresql://localhost:5432/jwtpoc
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=eoZ2FMAgeDUJT3DS8FQ3jTg3iFKlEMaSVWczHcWIJaE
# Access token expiration (15 minutes)
jwt.expiration=900000
# Refresh token expiration (24 hours)
jwt.refreshExpiration=86400000